name: flutter_news
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  json_annotation: ^4.8.1
  easy_localization: ^3.0.4
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
